### PR TITLE
Add a rewritten in Python SPK extractor

### PR DESCRIPTION
**Pull request by ostrosablin**
Hello! I've re-implemented in Python a SPK extractor from sourceforge by warchief-man. Not much, but I guess it'd be more helpful to have it as a Python tool, because it's a lot easier to use (especially under Linux), than building a Qt program.

Signed-off-by: Vitaly Ostrosablin <tmp6154@yandex.ru>

### CODE REVIEW

**Comment by minexew** [comment]
Bravo!

Just out of curiosity, why do you use the intermediate array in `read_c_string` (vs just appending to a _bytes_ object directly)? Is it because the list will allocate in a smarter way than the repeated append would?

**Comment by ostrosablin** [comment]
Actually, Python bytes is an immutable type, so each concatenation via "+" operator would produce a new bytes object, containing concatenation of two former objects, which tends to get slow very quickly due to a large amount of memory copying. A list join operation on other hand is faster, because I believe it's implemented inside the interpreter via a fast loop in C, which joins all child objects in one pass, without producing intermediate concatenations.

Not really a much of concern here (considering the sizes of strings), but I believe it's still considered a good practice in Python 3.

It's possible to rewrite through mutable bytearray, though, but I'm not sure if it will make any noticeable benefit, because there might be losses during casts of bytes to integers - bytearray seems to append only 0-255 integers.

**Comment by ostrosablin** [comment]
Yes, I've checked, in Python 3 it's still same as it was in Python 2.

Append-to-list and join method returns almost instantaneously.

```
>>> a = []
>>> def j():
...  global a
...  for i in range(1000000):
...   a.append(b"a")
...  a = b''.join(a)
... 
>>> j()
```

But concatenate-to-bytes method for 1000000 bytes is taking more than 30 seconds on my machine, due to excessive copying (it's more or less acceptable up to 100000 bytes, but as operands grow larger it becomes exponentially slower):

```
>>> for i in range(1000000):
...  b = b + b"a"
```

**Comment by minexew** [comment]
Perhaps one day I'll figure out how to cleanly merge Github pull requests :sweat_smile:

**Pull request merged**
