### PR TITLE
Add some src

### PR DESCRIPTION
**Pull request by Yoti**
Two files from the Symbian demo

### CODE REVIEW

**Comment by minexew** [comment]
Incredible! Would you agree to rename the directory to something like _Leaked_Source_ to clarify that it is not any official release?

**Comment by Yoti** [comment]
Yep.

**Comment by minexew** [comment]
Please have look if the modified commit is OK: https://github.com/minexew/Soft3D-RE/commit/251d015a5d7ed58166f59c09fee747c841cb1bfe. Unfortunately I cannot mark the PR as Merged on github because I rebased stuff manually.

Would you happen to also have the timestamps for these files? Do you know the encoding they are using?

**Comment by Yoti** [comment]
I think it's ok.

There are no timestamps for files itself for obvious reason.

SISX timestamp (from header) is 13-02-2009 09:46:06 (UTC).

Text encoding is the old standard Chinese one - GB2312.

**Comment by minexew** [comment]
Ok.

By the way, thanks to your contribution I was already able to disassemble quite a bit of `ep2050.sst`. Code [here](https://github.com/minexew/Soft3D-RE/blob/experimental/sst/Tools/sst.py), output [here](https://pastebin.com/s8kR185J). There is A LOT missing, but it was a fun little exercise.

So, thanks again.

**Comment by Yoti** [comment]
Try this one.
[ep2050.zip](https://github.com/minexew/Soft3D-RE/files/4899977/ep2050.zip)

**Pull request closed without merging**
